# dev

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  thymeleaf:
    cache: false   # 개발할 땐 캐시 끄기 (바로바로 반영)

    logging:
      level:
        root: ${LOGGING_LEVEL_ROOT:DEBUG}