spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/KNOU_CBT?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: blossom913@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
