# prod

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}


  thymeleaf:
    cache: true    # 운영에서는 캐시 켜기 (성능 ↑)

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  bucket:
    notice: notice
    exam: exam