spring:
  application:
    name: knou-cbt

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB

file:
  notice-dir: ${user.dir}/uploads/notice
  exam-dir: ${user.dir}/uploads/questions

# 마이그레이션 도구
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration