ALTER TABLE exam_question
    ADD COLUMN option_type VARCHAR(10) NOT NULL DEFAULT 'TEXT',
    ADD COLUMN image_layout VARCHAR(20);

ALTER TABLE exam_question
    ALTER COLUMN option1 TYPE VARCHAR(500),
    ALTER COLUMN option2 TYPE VARCHAR(500),
    ALTER COLUMN option3 TYPE VARCHAR(500),
    ALTER COLUMN option4 TYPE VARCHAR(500);
